apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tesla-http-proxy-helm.fullname" . }}-nginx
data:
  nginx.conf: |
    http {
        server {
            listen       80;
            server_name  localhost;

            location / {
                root /data/keypair;
                try_files /com.tesla.3p.public-key.pem =404;
            }

            error_page  404 /404.html;
            location = /404.html {
                root   /usr/share/nginx/html;
                internal;
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
                internal;
            }
        }
    }
