apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "tesla-http-proxy-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
  - tesla-proxy # maps to port 443 by default
  routes:
  - match: HostSNI(`*`)
    services:
    - name: tesla-http-proxy-tesla-http-proxy-helm
      port: 4430
  tls:
    passthrough: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "tesla-http-proxy-helm.fullname" . }}-nginx
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/.well-known/appspecific/com.tesla.3p.public-key.pem`)
    kind: Rule
    services:
    - name: {{ include "tesla-http-proxy-helm.fullname" . }}-nginx
      port: 80
  tls:
    secretName: {{ .Values.ingress.secretName }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "tesla-http-proxy-helm.fullname" . }}-8099
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`api-{{ .Values.ingress.host }}`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: tesla-http-proxy-tesla-http-proxy-helm
      port: 8099  # The port that the service listens on
  tls:
    secretName: {{ .Values.ingress.secretName }}
