apiVersion: v1
kind: Service
metadata:
  name: {{ include "tesla-http-proxy-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP  # You can change the service type as needed (ClusterIP, NodePort, LoadBalancer)
  ports:
    - port: 4430  # The port that the service listens on
      targetPort: 443  # The port your application listens on
      protocol: TCP
      name: http
    - port: 8099  # The port that the service listens on
      targetPort: 8099  # The port your application listens on
      protocol: TCP
      name: http
  selector:
      {{- include "tesla-http-proxy-helm.selectorLabels" . | nindent 4 }}
